In [ ]:
import os
# Mengimpor modul os (tidak digunakan langsung di kode ini, biasanya untuk operasi file/direktori)

import tensorflow as tf
# Mengimpor TensorFlow sebagai framework deep learning

from tensorflow import keras
# Mengimpor Keras API dari TensorFlow untuk membangun dan melatih model

import numpy as np
# Mengimpor NumPy untuk operasi numerik

import matplotlib.pyplot as plt
# Mengimpor Matplotlib untuk visualisasi data

In [ ]:
mnist = keras.datasets.mnist
# Mengakses dataset MNIST (dataset angka tulisan tangan 0–9)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# Memuat data training dan testing
# x berisi gambar 28x28, y berisi label angka 0–9

# print(x_train.shape, y_train.shape)
# (Komentar) Untuk melihat dimensi data training

x_train, x_test = x_train / 255.0, x_test / 255.0
# Normalisasi nilai piksel dari range 0–255 menjadi 0–1
# Ini membantu proses training agar lebih stabil

# for i in range(6):
#   plt.subplot(2, 3, i+1)
#   plt.imshow(x_train[i], cmap='gray')
# plt.show()
# (Komentar) Visualisasi 6 gambar pertama dari data training


model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    # Mengubah input gambar 2D (28x28) menjadi vektor 1D (784)

    keras.layers.Dense(128, activation='relu'),
    # Hidden layer dengan 128 neuron dan aktivasi ReLU

    keras.layers.Dense(10)
    # Output layer dengan 10 neuron (untuk klasifikasi digit 0–9)
])

# print(model.summary())
# (Komentar) Menampilkan arsitektur model dan jumlah parameter

# model = keras.Sequential()
# model.add(keras.layers.Flatten(input_shape=(28,28)))
# model.add(keras.layers.Dense(128, activation='relu'))
# model.add(keras.layers.Dense(10))
# (Komentar) Alternatif cara membangun model Sequential


loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# Fungsi loss untuk klasifikasi multi-kelas
# from_logits=True karena output model belum melalui Softmax

optimizer = keras.optimizers.Adam(learning_rate=0.001)
# Optimizer Adam dengan learning rate 0.001

metrics = ["accuracy"]
# Metrik evaluasi yang digunakan adalah akurasi


model.compile(loss=loss, optimizer=optimizer, metrics=metrics)
# Mengonfigurasi model dengan loss, optimizer, dan metrik


batch_size = 64
# Jumlah data dalam satu batch training

epochs = 5
# Jumlah iterasi training terhadap seluruh dataset


model.fit(
    x_train,
    y_train,
    batch_size=batch_size,
    epochs=epochs,
    shuffle=True,
    verbose=2
)
# Melatih model menggunakan data training
# shuffle=True agar data diacak setiap epoch


model.evaluate(x_test, y_test, batch_size=batch_size, verbose=2)
# Mengevaluasi performa model menggunakan data testing


probability_model = keras.models.Sequential([
    model,
    keras.layers.Softmax()
])
# Membuat model baru dengan tambahan Softmax
# Tujuannya untuk mengubah output logits menjadi probabilitas


predictions = probability_model(x_test)
# Melakukan prediksi probabilitas pada data testing

pred0 = predictions[0]
# Mengambil probabilitas dari data testing pertama

print(pred0)
# Menampilkan probabilitas untuk tiap kelas (0–9)

label0 = np.argmax(pred0)
# Mengambil indeks dengan probabilitas tertinggi sebagai label prediksi

print(label0)
# Menampilkan label hasil prediksi


predictions = model.predict(x_test, batch_size=batch_size)
# Melakukan prediksi langsung menggunakan model (masih berupa logits)

predictions = tf.nn.softmax(predictions)
# Mengubah logits menjadi probabilitas menggunakan Softmax

pred0 = predictions[0]
# Mengambil probabilitas prediksi pertama

print(pred0)
# Menampilkan probabilitas kelas

label0 = np.argmax(pred0)
# Mengambil label prediksi dengan probabilitas tertinggi

print(label0)
# Menampilkan label hasil prediksi


pred05s = predictions[0:5]
# Mengambil prediksi untuk 5 data pertama

print(pred05s.shape)
# Menampilkan bentuk data (5, 10)

label05s = np.argmax(pred05s, axis=1)
# Mengambil label prediksi untuk 5 data sekaligus

print(label05s)
# Menampilkan label prediksi untuk 5 gambar pertama


# Ringkasan:
# Kode ini membangun dan melatih model neural network sederhana
# untuk klasifikasi angka tulisan tangan (MNIST) menggunakan TensorFlow/Keras.
# Alur utama meliputi:
# - Memuat dan menormalisasi dataset MNIST
# - Membangun model Sequential (Flatten + Dense)
# - Melatih dan mengevaluasi model
# - Melakukan prediksi dan mengubah output logits menjadi probabilitas
# Kode ini merupakan contoh dasar penerapan deep learning
# untuk masalah klasifikasi citra.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
938/938 - 6s - 6ms/step - accuracy: 0.9171 - loss: 0.2983
Epoch 2/5
938/938 - 4s - 4ms/step - accuracy: 0.9611 - loss: 0.1327
Epoch 3/5
938/938 - 6s - 6ms/step - accuracy: 0.9725 - loss: 0.0925
Epoch 4/5
938/938 - 4s - 4ms/step - accuracy: 0.9793 - loss: 0.0694
Epoch 5/5
938/938 - 4s - 4ms/step - accuracy: 0.9843 - loss: 0.0542
157/157 - 1s - 4ms/step - accuracy: 0.9762 - loss: 0.0769
tf.Tensor(
[1.1983265e-07 5.1476232e-09 1.2201431e-06 7.7713827e-05 1.4181381e-09
 2.1245776e-07 7.4046802e-12 9.9991733e-01 4.8707028e-07 2.8046445e-06], shape=(10,), dtype=float32)
7
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
tf.Tensor(
[1.1983265e-07 5.1476232e-09 1.2201431e-06 7.7713827e-05 1.4181381e-09
 2.1245776e-07 7.4046802e-12 9.9991733e-01 4.8707028e-07 2.8046445e-06], shape=(10,), dtype=float32)
7
(5, 10)
[7 2 1 0 4]
