In [ ]:
import tensorflow as tf
# Mengimpor library TensorFlow dan memberinya alias 'tf'

In [ ]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
# Membuat tensor konstan 2D (matrix 2x3)

print(x)
# Menampilkan isi tensor x ke layar


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.eye(4)
# Membuat matriks identitas 4x4 (diagonal bernilai 1, lainnya 0)

print(x)
# Menampilkan matriks identitas

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [ ]:
x = tf.random.normal((3,3), mean=0, stddev=1)
# Membuat tensor acak berukuran 3x3 dengan distribusi normal
# mean = 0 dan standar deviasi = 1

print(x)
# Menampilkan tensor acak

tf.Tensor(
[[-0.90215147  0.65003896 -0.75382054]
 [ 0.8780161  -0.42819136 -1.1134285 ]
 [-0.20873266 -0.5005242  -0.4548434 ]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.range(2)
# Membuat tensor 1D berisi nilai [0, 1]

print(x)
# Menampilkan tensor range

x = tf.cast(x, dtype=tf.float32)
# Mengubah tipe data tensor dari integer ke float32

print(x)
# Menampilkan tensor setelah casting

tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([0. 1.], shape=(2,), dtype=float32)


In [ ]:
x = tf.constant([1, 2, 3])
# Membuat tensor 1D berisi vektor [1, 2, 3]

y = tf.constant([4, 5, 6])
# Membuat tensor 1D berisi vektor [4, 5, 6]

z = tf.tensordot(x, y, axes=1)
# Melakukan operasi dot product antara x dan y
# axes=1 artinya menjumlahkan hasil perkalian elemen yang bersesuaian

print(z)
# Menampilkan hasil dot product (skalar)

print(tf.add(x, y))
# Menjumlahkan tensor x dan y secara elemen-per-elemen

tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
x = tf.random.normal((2,2))
# Membuat tensor acak 2x2

print(x)
# Menampilkan tensor TensorFlow

x = x.numpy()
# Mengonversi tensor TensorFlow menjadi NumPy array

print(x)
# Menampilkan NumPy array

x = tf.convert_to_tensor(x)
# Mengonversi kembali NumPy array menjadi TensorFlow tensor

tf.Tensor(
[[ 0.44687945  0.49041295]
 [-0.39820674  0.5082843 ]], shape=(2, 2), dtype=float32)
[[ 0.44687945  0.49041295]
 [-0.39820674  0.5082843 ]]


In [ ]:
# Ringkasan:
# Kode ini menunjukkan penggunaan dasar TensorFlow untuk:
# 1. Membuat tensor konstan, matriks identitas, dan tensor acak
# 2. Menghasilkan tensor berurutan menggunakan tf.range
# 3. Melakukan konversi tipe data tensor (casting)
# 4. Melakukan operasi vektor seperti penjumlahan dan dot product
# 5. Mengonversi data antara TensorFlow Tensor dan NumPy Array
# Kode ini berguna sebagai pengenalan dasar manipulasi tensor
# sebelum masuk ke tahap Machine Learning atau Deep Learning.
